name 'hello_chef_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hello_chef_server'
long_description 'Installs/Configures hello_chef_server'
version '0.1.0'

depends 'apt', '~> 4.0.1'
depends 'firewall', '~> 2.5.2'
depends 'mysql', '7.2.0'
